#!/usr/bin/env bash
# Build edim-dde-{ai,domain,api} wheels into deploy/databricks-app/vendor/
# and write requirements.vendor.txt with exact filenames (pip has no globs).
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/../.." && pwd)"          # edim-dde-api
PARENT="$(cd "$ROOT/.." && pwd)"                     # workspace with siblings
VENDOR="$ROOT/deploy/databricks-app/vendor"
VENDOR_REQ="$ROOT/deploy/databricks-app/requirements.vendor.txt"

AI="${EDIM_AI_PATH:-$PARENT/edim-dde-ai}"
DOMAIN="${EDIM_DOMAIN_PATH:-$PARENT/edim-dde-domain}"
API="$ROOT"

for d in "$AI" "$DOMAIN" "$API"; do
  if [[ ! -d "$d" ]]; then
    echo "error: missing package path: $d" >&2
    echo "Set EDIM_AI_PATH / EDIM_DOMAIN_PATH if siblings are not next to edim-dde-api." >&2
    exit 1
  fi
done

PYTHON="${PYTHON:-python3}"
rm -rf "$VENDOR"
mkdir -p "$VENDOR"

build_one() {
  local src="$1"
  echo "==> building wheel in $src"
  (
    cd "$src"
    rm -rf dist
    "$PYTHON" -m pip install -q build
    "$PYTHON" -m build --wheel
    cp -v dist/*.whl "$VENDOR/"
  )
}

build_one "$AI"
build_one "$DOMAIN"
build_one "$API"

# Local Docker MkDocs guide (not Databricks Apps)
rm -rf "$ROOT/deploy/databricks-app/guide-docs" "$ROOT/deploy/docker/guide-docs"
PYTHON="$PYTHON" EDIM_DOMAIN_PATH="$DOMAIN" "$ROOT/deploy/scripts/build_guide_site.sh"

{
  echo "# Generated by deploy/scripts/build_vendor_wheels.sh — do not edit"
  echo "# Install order: ai → domain → api"
  for pattern in edim_dde_ai edim_dde_domain edim_dde_api; do
    for whl in "$VENDOR"/${pattern}-*.whl; do
      [[ -f "$whl" ]] || continue
      echo "./vendor/$(basename "$whl")"
    done
  done
} > "$VENDOR_REQ"

echo ""
echo "Wrote $VENDOR_REQ"
echo "Vendor wheels:"
ls -la "$VENDOR"
echo ""
echo "Next:"
echo "  • Apps guide: make copy-guide-site then include guide-site/ in apps-sync"
echo "  • Databricks Apps: sync deploy/databricks-app/ (vendor/ + requirements*.txt)"
echo "  • Docker MkDocs guide: make compose-up -> http://127.0.0.1:8080/guide/"
echo "  • Guide source: edim-dde-domain/docs/ (+ mkdocs.yml)"
